[tool.poetry]
name = "deltadb"
version = "0.1.6"
description = ""
authors = ["uname-n <noreply@github.com>"]
readme = "README.md"
packages = [{include = "deltadb"}]

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.4.1"
deltalake = "^0.18.2"
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
